### ISSUE TITLE
Textblock not found on custom chests

### ISSUE THREAD

**Issue by TheFuneralPortrait** [syntax53/MMUD-Explorer#17]
I made a new chest which works correctly when tested in game, but would say the textblock is not found when I exported and tried to look at it in MME. After some more time trying many different textblocks, I'm having the same end result.

Is there possibly a bug with MME where it's not correctly recognizing textblocks out of the stock ranges? Not sure where to go from here, as the chests work, but it's not ideal to release them without the export being usable as a reference.

**Comment by syntax53** [comment]
Is the chest obtainable in game?  obtainable through normal means?  Did you try turning on the option to show items not in game (MME settings option)?  If NMR isn't detecting it as being in-game there is a chance it's not making into the export file.

**Comment by TheFuneralPortrait** [comment]
I PMed you (on Mudinfo) a link to an MME export that still has the item in it. Myself and Winterhawk both tried a bunch of different configurations for the textblocks, essentially all of which functioned/opened correctly on WG test realms, but none of which got us past the error when you try to look at the chest textblock in MME. This is one of those permutations.

**Comment by syntax53** [comment]
In order to get that item to show up in MME, I had to disable the option that only shows items in the game.  Meaning the item is not being detected as being obtainable within the game, which could be why the textblock is not getting exported.

So again, is the item actually obtainable?  If it is, how so?  Because NMR isn't picking it up and could be an enhancement needed there.  If it isn't, try adding the item has a drop to a mob and then doing an export again and see if everything gets exported as expected.

**Comment by TheFuneralPortrait** [comment]
Originally the item was not obtainable, as we had considered adding it as a quest reward and hadn't assigned it to drop from any monster. I added the drop to a boss as you requested, re-exported, and sure enough I can click through in MME with no textblock error. 

Hope this helps for your NMR adjustments and thanks for the help!
